name: costus
description: "Costus"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  bloc: ^8.1.3
  carousel_slider: ^5.0.0
  cloud_firestore:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_email_sender: ^6.0.2
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  meta: ^1.11.0
  pdf: ^3.10.8
  pie_chart: ^5.4.0
  printing: ^5.12.0
  purchases_flutter: ^8.1.6
  purchases_ui_flutter: ^8.1.6
  share_plus: ^10.0.3
  super_tooltip: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FAF3F5"
  image: assets/images/splash.png
  android_12: 
    image: assets/images/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/primary/
    - assets/images/secondary/
    - assets/images/tertiary/
    - assets/images/why/
